#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,16.3,0
#
Button_Hwi.xem3: package/cfg/Button_Hwi.xem3.mak

clean::
	-$(RM) package/cfg/Button_Hwi.xem3.mak
